org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=1

kotlin.daemon.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

android.useAndroidX=true
android.nonTransitiveRClass=true

android.builtInKotlin=false
android.newDsl=false
kotlin.compiler.execution.strategy=in-process
